# Generated by Django 3.1.7 on 2021-02-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='need_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.need'),
        ),
    ]
