# Generated by Django 3.1.7 on 2021-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='role',
            field=models.TextField(default='tools'),
        ),
    ]
