# Generated by Django 3.1.7 on 2021-02-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_services_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_active',
            field=models.BooleanField(default=True),
        ),
    ]
