# Generated by Django 3.1.7 on 2021-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_services_services_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_active',
            field=models.BooleanField(default=True),
        ),
    ]
