# Generated by Django 3.1.7 on 2021-02-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_services_image_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='marquee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('info_active', models.BooleanField(default=True)),
                ('logos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='softwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumb_image', models.ImageField(upload_to='')),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('softwares_active', models.BooleanField(default=True)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('image_3', models.ImageField(upload_to='')),
                ('features', models.TextField()),
                ('sub_features_head', models.CharField(max_length=50)),
                ('sub_features_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('count', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='description_1',
        ),
        migrations.AddField(
            model_name='services',
            name='description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='thumb_image',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='role',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.services')),
            ],
        ),
    ]
