# Generated by Django 3.1.7 on 2021-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210225_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='thumb_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
