# Generated by Django 3.1.7 on 2021-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210225_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description_2',
            field=models.TextField(null=True),
        ),
    ]
