# Generated by Django 3.1.7 on 2021-02-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210226_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='need_name',
            new_name='name',
        ),
    ]
