# Generated by Django 3.1.7 on 2021-02-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210226_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='need_name',
            new_name='name',
        ),
    ]
