# Generated by Django 3.1.7 on 2021-02-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20210226_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='name',
        ),
    ]
