# Generated by Django 3.1.7 on 2021-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210227_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwares',
            old_name='features',
            new_name='features_content',
        ),
        migrations.RenameField(
            model_name='softwares',
            old_name='sub_features_head',
            new_name='features_head',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='sub_features_content',
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='profile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
