# Generated by Django 3.1.7 on 2021-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210227_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='features_content',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='features_head',
        ),
    ]
