# Generated by Django 3.1.7 on 2021-02-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210227_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='content',
        ),
        migrations.RemoveField(
            model_name='features',
            name='head',
        ),
        migrations.AddField(
            model_name='features',
            name='feature_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='feature_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='softwares',
            name='feature_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.services'),
        ),
    ]
