# Generated by Django 3.1.7 on 2021-02-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210227_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwares',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.features'),
        ),
    ]
