# Generated by Django 3.1.7 on 2021-03-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210227_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwares',
            name='head',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='image_3',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.need'),
        ),
    ]
