# Generated by Django 3.1.7 on 2021-03-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210301_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwares',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.features'),
        ),
    ]
