# Generated by Django 3.1.7 on 2021-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_softwares_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwares',
            name='head',
        ),
        migrations.AddField(
            model_name='softwares',
            name='head',
            field=models.ManyToManyField(to='website.features'),
        ),
    ]
