# Generated by Django 3.1.7 on 2021-03-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210301_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('head', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='')),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('mailid', models.CharField(max_length=30)),
                ('skypeid', models.CharField(max_length=15)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('profile', models.CharField(max_length=50, null=True)),
                ('profile_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='marquee',
            old_name='logos',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='position',
        ),
        migrations.RemoveField(
            model_name='about',
            name='profile',
        ),
        migrations.AddField(
            model_name='about',
            name='description_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='header',
            name='header_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marquee',
            name='logo_active',
            field=models.BooleanField(default=True),
        ),
    ]
