# Generated by Django 3.1.7 on 2021-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20210318_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_active',
            field=models.BooleanField(default=True),
        ),
    ]
