# Generated by Django 3.1.7 on 2021-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_about_about_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='head_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carousel',
            name='head_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='carousel',
            name='head_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
