# Generated by Django 3.1.7 on 2021-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20210318_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='head_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='head_3',
            field=models.TextField(blank=True),
        ),
    ]
