# Generated by Django 3.1.7 on 2021-04-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20210318_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='header_active',
        ),
    ]
