# Generated by Django 3.1.7 on 2021-04-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_remove_header_header_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwares',
            name='description_active',
            field=models.BooleanField(default=True),
        ),
    ]
