# Generated by Django 3.1.7 on 2021-04-18 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_softwares_description_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.services'),
        ),
    ]
