# Generated by Django 3.1.7 on 2021-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20210418_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='role',
        ),
        migrations.RemoveField(
            model_name='services',
            name='tools',
        ),
        migrations.AddField(
            model_name='services',
            name='description_3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='head_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='head_1_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='head_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='head_2_info',
            field=models.TextField(null=True),
        ),
    ]
