# Generated by Django 3.1.7 on 2021-04-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_auto_20210426_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='name',
            new_name='head',
        ),
    ]
