# Generated by Django 3.1.7 on 2021-04-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20210426_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='progress',
        ),
    ]
