# Generated by Django 3.1.7 on 2021-05-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20210504_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='heading',
            new_name='name',
        ),
        migrations.AddField(
            model_name='about',
            name='description_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='disclaimer',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(default=True),
        ),
    ]
