# Generated by Django 3.1.7 on 2021-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20210506_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField()),
                ('description_3', models.TextField(blank=True)),
                ('disclaimer', models.TextField(default=True)),
                ('mission', models.TextField(default=True)),
                ('vision', models.TextField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
