# Generated by Django 3.1.7 on 2021-05-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20210508_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=5)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.services')),
            ],
        ),
    ]
