# Generated by Django 3.1.7 on 2021-05-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='name',
        ),
        migrations.AddField(
            model_name='progress',
            name='services',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='website.services'),
        ),
    ]
