# Generated by Django 3.1.7 on 2021-05-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20210508_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='services',
        ),
        migrations.AddField(
            model_name='progress',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.services'),
        ),
    ]
