# Generated by Django 3.1.7 on 2021-05-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_auto_20210508_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='percentage',
            field=models.CharField(default=True, max_length=3),
        ),
        migrations.DeleteModel(
            name='progress',
        ),
    ]
