# Generated by Django 3.1.7 on 2021-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_auto_20210509_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='members',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='members',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
