# Generated by Django 3.1.7 on 2021-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_auto_20210510_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_4',
            field=models.TextField(blank=True),
        ),
    ]
