# Generated by Django 3.1.7 on 2021-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_auto_20210512_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='image',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
