# Generated by Django 3.1.7 on 2021-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_values_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='image',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
