# Generated by Django 3.1.7 on 2021-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_auto_20210512_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
