# Generated by Django 3.1.2 on 2021-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
