# Generated by Django 3.1.2 on 2021-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_user_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
