# Generated by Django 3.1.2 on 2021-06-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_user_profile_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='timestamp',
        ),
    ]
